// Every bug below is a real, well-documented JS gotcha -- not a made-up
// puzzle. Each has exactly one unambiguous buggy line so a click either
// clearly hits it or clearly doesn't.
const BUGS = [
  {
    code: [
      'function sumArray(arr) {',
      '  let total = 0;',
      '  for (let i = 0; i <= arr.length; i++) {',
      '    total += arr[i];',
      '  }',
      '  return total;',
      '}',
    ],
    bugLine: 2,
    explain: 'Off-by-one: `i <= arr.length` runs one iteration too many, so arr[arr.length] is undefined and total becomes NaN.',
  },
  {
    code: [
      'function checkAccess(role) {',
      '  if (role = "admin") {',
      '    return "Access granted";',
      '  }',
      '  return "Access denied";',
      '}',
    ],
    bugLine: 1,
    explain: 'Assignment, not comparison: `role = "admin"` overwrites role and always evaluates truthy. Should be `===`.',
  },
  {
    code: [
      'function getDiscount(tier) {',
      '  let discount = 0;',
      '  switch (tier) {',
      '    case "gold":',
      '      discount = 20;',
      '    case "silver":',
      '      discount = 10;',
      '      break;',
      '    default:',
      '      discount = 0;',
      '  }',
      '  return discount;',
      '}',
    ],
    bugLine: 4,
    explain: 'Missing `break` after the gold case -- it falls through and silver\'s `discount = 10` overwrites the 20 that was just set.',
  },
  {
    code: [
      'function isExactTotal(a, b, expected) {',
      '  const sum = a + b;',
      '  if (sum === expected) {',
      '    return "Match!";',
      '  }',
      '  return "No match";',
      '}',
      '',
      'isExactTotal(0.1, 0.2, 0.3); // expected "Match!"',
    ],
    bugLine: 2,
    explain: '0.1 + 0.2 is 0.30000000000000004 in floating point -- === against 0.3 fails. Classic IEEE-754 gotcha.',
  },
  {
    code: [
      'async function getUserName(id) {',
      '  const response = fetch(`/api/users/${id}`);',
      '  const data = await response.json();',
      '  return data.name;',
      '}',
    ],
    bugLine: 1,
    explain: 'Missing `await` on fetch() -- response is a pending Promise, not a Response, so .json() isn\'t a valid call on it.',
  },
  {
    code: [
      'function createTimers() {',
      '  for (var i = 0; i < 3; i++) {',
      '    setTimeout(function () {',
      '      console.log("Timer " + i);',
      '    }, 1000);',
      '  }',
      '}',
    ],
    bugLine: 1,
    explain: '`var` is function-scoped, so all three closures share the same i -- by the time the timeouts fire, i is already 3.',
  },
  {
    code: [
      'function sortScores(scores) {',
      '  return scores.sort();',
      '}',
      '',
      'sortScores([40, 100, 5, 25]); // expected [5, 25, 40, 100]',
    ],
    bugLine: 1,
    explain: '.sort() with no comparator sorts as strings -- [100, 25, 40, 5], not numeric order.',
  },
  {
    code: [
      'function factorial(n) {',
      '  return n * factorial(n - 1);',
      '}',
    ],
    bugLine: 1,
    explain: 'No base case -- this recurses forever (well, until a stack overflow) instead of stopping at n <= 1.',
  },
  {
    code: [
      'class Timer {',
      '  constructor() {',
      '    this.seconds = 0;',
      '  }',
      '  start() {',
      '    setInterval(function () {',
      '      this.seconds++;',
      '    }, 1000);',
      '  }',
      '}',
    ],
    bugLine: 5,
    explain: 'A regular `function` callback gets its own `this` (usually undefined/window), losing the Timer instance. Needs an arrow function.',
  },
  {
    code: [
      'function removeNegatives(nums) {',
      '  nums.forEach((n, i) => {',
      '    if (n < 0) {',
      '      nums.splice(i, 1);',
      '    }',
      '  });',
      '  return nums;',
      '}',
    ],
    bugLine: 3,
    explain: 'Splicing while forEach is iterating shifts every later index back by one -- adjacent negatives get skipped.',
  },
]
